name: test

on:
  # schedule:
    # - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap
        
      - name: 测试ip
        run: |
          cd $GITHUB_WORKSPACE
          bash ./py/iptv源收集检测/主频道/专享频道/py/组播/zubo1.sh
          # time=$(date +%Y/%m/%d)
          # echo "浙江频道 $time 更新,#genre#" > zubo.txt
          # cat txt/浙江.txt >> zubo.txt
          cat py/iptv源收集检测/主频道/专享频道/py/组播/ip//浙江电信_config.txt py/iptv源收集检测/主频道/专享频道/py/组播/ip//江苏电信_config.txt       

      - name: 更新ip
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新ip_config"
#          git push
