name: zubo1

on:
  # schedule:
  #   - cron: '10 3,12 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap
        
      - name: 获取测试组播源
        run: |
          cd $GITHUB_WORKSPACE
          bash ./py/iptv源收集检测/主频道/专享频道/py/组播/zubo1.sh
          cat py/iptv源收集检测/主频道/专享频道/py/组播/txt/湖北电信.txt py/iptv源收集检测/主频道/专享频道/py/组播/txt/浙江电信.txt py/iptv源收集检测/主频道/专享频道/py/组播/txt/江苏电信.txt py/iptv源收集检测/主频道/专享频道/py/组播/txt/四川电信.txt > py/iptv源收集检测/主频道/专享频道/py/组播/txt/zubo1.txt
          
      - name: 更新组播源
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新组播源"
          git push
